// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhEKxbOhJidjAmAytoy9NlvyHQl9t-IXk',
    appId: '1:190990032924:web:2fa679f3d805675fc27fd9',
    messagingSenderId: '190990032924',
    projectId: 'iot-adapter-54a9a',
    authDomain: 'iot-adapter-54a9a.firebaseapp.com',
    databaseURL: 'https://iot-adapter-54a9a-default-rtdb.firebaseio.com',
    storageBucket: 'iot-adapter-54a9a.appspot.com',
    measurementId: 'G-Y5Y6Q4WGXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCapzvr4NibG_WJSW4cK6qWSnfwM3RfCws',
    appId: '1:190990032924:android:10576396380d190bc27fd9',
    messagingSenderId: '190990032924',
    projectId: 'iot-adapter-54a9a',
    databaseURL: 'https://iot-adapter-54a9a-default-rtdb.firebaseio.com',
    storageBucket: 'iot-adapter-54a9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqCIg_bPwzGmpaGBKAlFopbiJ9k9V9XNg',
    appId: '1:190990032924:ios:5c7ea7501211814fc27fd9',
    messagingSenderId: '190990032924',
    projectId: 'iot-adapter-54a9a',
    databaseURL: 'https://iot-adapter-54a9a-default-rtdb.firebaseio.com',
    storageBucket: 'iot-adapter-54a9a.appspot.com',
    iosBundleId: 'com.example.iotAdapter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqCIg_bPwzGmpaGBKAlFopbiJ9k9V9XNg',
    appId: '1:190990032924:ios:5c7ea7501211814fc27fd9',
    messagingSenderId: '190990032924',
    projectId: 'iot-adapter-54a9a',
    databaseURL: 'https://iot-adapter-54a9a-default-rtdb.firebaseio.com',
    storageBucket: 'iot-adapter-54a9a.appspot.com',
    iosBundleId: 'com.example.iotAdapter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhEKxbOhJidjAmAytoy9NlvyHQl9t-IXk',
    appId: '1:190990032924:web:cb1b7a4a09dceb6fc27fd9',
    messagingSenderId: '190990032924',
    projectId: 'iot-adapter-54a9a',
    authDomain: 'iot-adapter-54a9a.firebaseapp.com',
    databaseURL: 'https://iot-adapter-54a9a-default-rtdb.firebaseio.com',
    storageBucket: 'iot-adapter-54a9a.appspot.com',
    measurementId: 'G-N709YN79VX',
  );

}